# Generated by Django 2.2.1 on 2019-05-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='article',
            name='password',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='密码'),
        ),
    ]
